### PR TITLE
Removed the distribution points implementation

### PR DESCRIPTION
**Pull request by vanlooverenkoen**

### CODE REVIEW

**Review by ikbendewilliam — APPROVED** [review]
You could've added a parameter, but commenting it out is fine for me

**Comment by NicolaVerbeeck** [comment]
Commenting out is never fine with VCSs

**Review by NicolaVerbeeck — CHANGES_REQUESTED** [review]
Don't comment out code. You could also just return a raw byte representation that end-users can then parse

**Comment by vanlooverenkoen** [comment]
I will just remove everything. And add an extra todo. Because the raw bytes are not needed for us at the moment. and currently we will not merge upstream

**Review by ikbendewilliam — APPROVED** [review]

**Pull request merged**
